config/routes.rb
Rails.application.routes.draw do

  get 'songs/index'

  get 'songs/upload'

  get 'songs/delete'

  devise_for :artists 
  devise_for :listeners

  root 'welcome#index'

  resources :artists
  resources :listeners

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :songs
end

app/models/listener.rb
class Listener < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
#
  # def current_artist
  #   @current_artist ||= Artist.find_by(id: session[:artist_id])
  # end
#
#   helper_method :current_artist
#
#   def current_listener
#     @current_listener ||= Listener.find_by(id: session[:listener_id])
#   end
#
#   helper_method :current_listener
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_artist!
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
      @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:first_name, :last_name, :artist_name, :email)
    end
end

app/controllers/listeners_controller.rb
class ListenersController < ApplicationController
  before_action :authenticate_listener!
  before_action :set_listener, only: [:show, :edit, :update, :destroy]

  # GET /listeners
  # GET /listeners.json
  def index
    @listeners = Listener.all
  end

  # GET /listeners/1
  # GET /listeners/1.json
  def show
  end

  # GET /listeners/new
  def new
    @listener = Listener.new
  end

  # GET /listeners/1/edit
  def edit
  end

  # POST /listeners
  # POST /listeners.json
  def create
    @listener = Listener.new(listener_params)

    respond_to do |format|
      if @listener.save
        format.html { redirect_to @listener, notice: 'Listener was successfully created.' }
        format.json { render :show, status: :created, location: @listener }
      else
        format.html { render :new }
        format.json { render json: @listener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listeners/1
  # PATCH/PUT /listeners/1.json
  def update
    respond_to do |format|
      if @listener.update(listener_params)
        format.html { redirect_to @listener, notice: 'Listener was successfully updated.' }
        format.json { render :show, status: :ok, location: @listener }
      else
        format.html { render :edit }
        format.json { render json: @listener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listeners/1
  # DELETE /listeners/1.json
  def destroy
    @listener.destroy
    respond_to do |format|
      format.html { redirect_to listeners_url, notice: 'Listener was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listener
      @listener = Listener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listener_params
      params.require(:listener).permit(:first_name, :last_name, :email)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController





  def index
    @songs = Songs.all
  end

  def upload
  end

  def delete
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @listener = current_listener
    @artist = current_artist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/listeners_helper.rb
module ListenersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :artist_name %><br>
    <%= f.text_field :artist_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/_welcome.html.erb
<% if artist_signed_in? %>
      <%= link_to "Artist Sign Out", destroy_artist_session_path, :method => :delete %>
    <% else %>
      <%=link_to "Artist Sign In", new_artist_session_path %></li>
    <% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<% if artist_signed_in? %>
  <p id="notice"><%= notice %></p>

  <h1>Listing Artists</h1>

  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Artist name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td><%= artist.first_name %></td>
          <td><%= artist.last_name %></td>
          <td><%= artist.artist_name %></td>
          <td><%= artist.email %></td>
          <td><%= link_to 'Show', artist %></td>
          <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
          <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Artist', new_artist_path %>
<% end %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<%= render partial: 'shared/navbar' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @artist.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @artist.last_name %>
</p>

<p>
  <strong>Artist name:</strong>
  <%= @artist.artist_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @artist.email %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IndieApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: 'shared/navbar' %>

  <%= yield %>

  </body>
</html>

app/views/listeners/_form.html.erb
<%= form_for(@listener) do |f| %>
  <% if @listener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listener.errors.count, "error") %> prohibited this listener from being saved:</h2>

      <ul>
      <% @listener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listeners/edit.html.erb
<h1>Editing Listener</h1>

<%= render 'form' %>

<%= link_to 'Show', @listener %> |
<%= link_to 'Back', listeners_path %>

app/views/listeners/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Listing Listeners</h1>

  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @listeners.each do |listener| %>
        <tr>
          <td><%= listener.first_name %></td>
          <td><%= listener.last_name %></td>
          <td><%= listener.email %></td>
          <td><%= link_to 'Show', listener %></td>
          <td><%= link_to 'Edit', edit_listener_path(listener) %></td>
          <td><%= link_to 'Destroy', listener, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Listener', new_listener_path %>

app/views/listeners/new.html.erb
<h1>New Listener</h1>

<%= render 'form' %>

<%= link_to 'Back', listeners_path %>

app/views/listeners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @listener.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @listener.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @listener.email %>
</p>

<%= link_to 'Edit', edit_listener_path(@listener) %> |
<%= link_to 'Back', listeners_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-sticky">
  <% if listener_signed_in? %>
  <li><%= link_to "Listener Logout", destroy_listener_session_path, :method => :delete %></li>
  <% end %>
  <% if artist_signed_in? %>
  <li><%= link_to "Artist Logout", destroy_artist_session_path, :method => :delete %></li>
  <% end %>
</nav>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>


<ul>
  <% songs.each do |song| %>
    <li><%= song.key %> - <%= link_to "Delete",  "songs/delete/?song=" + song.key, :confirm => 'Are you sure you want to delete ' + song.key + '?' %></li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div class="container">
 <div class="text-vertical-center col-md-6" id="welcome-content">
  <h1>IndieApp</h1>
    <br>
  <h3>Streaming APP for Local Artist</h3>

  <h4>Select one to get started</h4>

  <%= button_to "Listener", new_listener_session_path %>
  <%= button_to "Artist", new_artist_session_path %>

 </div>
</div>